version: '3.2'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./images/nginx:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx

  php:
    build: .
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./www:/var/www

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret

  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    links:
      - mysql:db
    ports:
      - 8000:80
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
    depends_on:
      - mysql

  redis:
    image: redis:5.0-alpine
    restart: always
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis-admin:
    image: erikdubbelboer/phpredisadmin
    restart: always
    depends_on:
      - redis
    ports:
      - "8083:80"
    environment:
      - REDIS_1_HOST=redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"