version: "3.2"

services:
  nginx:
    image: nginx:1.17.10
    ports:
      - "82:80"
      - "444:443"
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./images/nginx:/etc/nginx/conf.d
      - ./www:/var/www
#      - ./.dev/logs:/var/log/nginx
    depends_on:
      - php
      - mysql
    logging:
      driver: "none"

  php:
    image: 13123123/uberserver:latest
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./www:/var/www
      - ./.dev/.data/backup:/var/www/project/backend/runtime/backup
    depends_on:
      - mysql
      - redis
    logging:
      driver: "none"

  supervisor:
    image: 13123123/uberserver:latest
    volumes:
      - ./images/worker/supervisor/config:/etc/supervisor/conf.d
#      - ./.dev/logs:/var/log/supervisor
      - ./www:/var/www
    command: /usr/bin/supervisord
    depends_on:
      - php
      - mysql
      - redis
    logging:
      driver: "none"

  mysql:
    image: mysql:5.7.32
    ports:
      - "3306:3306"
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./.dev/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret
    logging:
      driver: "none"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    links:
      - mysql:db
    ports:
      - 8000:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
    depends_on:
      - mysql
    logging:
      driver: "none"

  redis:
    image: redis:5.0.9-alpine
    ports:
      - "6379:6379"
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    logging:
      driver: "none"

  redis-admin:
    image: erikdubbelboer/phpredisadmin:v1.13.1
    depends_on:
      - redis
    ports:
      - "8083:80"
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    environment:
      - REDIS_1_HOST=redis
    logging:
      driver: "none"
